simple

diff --git a/.buildkite/pipeline.yml b/.buildkite/pipeline.yml
--- a/.buildkite/pipeline.yml
+++ b/.buildkite/pipeline.yml
@@ -23,20 +23,20 @@ steps:
   - label: "Run Script"
     command: script.sh
 
-  - label: "Debug: Check Metadata"
-    command: |
-      echo "Attempting to retrieve name from metadata..."
-      name=$(buildkite-agent meta-data get "name")
-      echo "Retrieved name: $name"
+  # - label: "Debug: Check Metadata"
+  #   command: |
+  #     echo "Attempting to retrieve name from metadata..."
+  #     name=$(buildkite-agent meta-data get name)
+  #     echo "Retrieved name: $name"
 
-  - label: "Set Name Environment Variable"
-    command: |
-      name=$(buildkite-agent meta-data get "name")
-      if [ -z "$name" ]; then
-        echo "Error: No name provided"
-        exit 1
-      fi
-      echo "Name set to: $name"
+  # - label: "Set Name Environment Variable"
+  #   command: |
+  #     name=$(buildkite-agent meta-data get "name")
+  #     if [ -z "$name" ]; then
+  #       echo "Error: No name provided"
+  #       exit 1
+  #     fi
+  #     echo "Name set to: $name"
 
   - label: "Run Hello Binary Inside Docker Container"
     plugins:
